CREATE TABLE TRANSFER_BUY
(

 BUY_ID INT IDENTITY(1,1) PRIMARY KEY,
 NP_NAME VARCHAR(50)  NOT NULL,
 Con_type VARCHAR(50)  NOT NULL,
 Year INT  NOT NULL,
 Salary MONEY  NOT NULL,
 Fee MONEY  NOT NULL


)

CREATE TABLE TRANSFER_SELL(

 Sell_ID INT IDENTITY(1,1) PRIMARY KEY,

 P_ID INT NOT NULL FOREIGN KEY REFERENCES Player (P_ID),
 P_NAME VARCHAR(50) NOT NULL,
 CON_TYPE VARCHAR(50) NOT NULL,
 FEE MONEY NOT NULL




)


CREATE TABLE MEDIA(

M_ID INT IDENTITY (1,1) PRIMARY KEY,
M_TYPE VARCHAR(50) NOT NULL,
CON_YEAR VARCHAR(50) NOT NULL,
REVENUE MONEY NOT NULL





)


CREATE TABLE GROUND_AND_GYM(

  G_NO INT IDENTITY (1,1) PRIMARY KEY,

  G_NAME VARCHAR(50) NOT NULL,
  TYPE VARCHAR(50) NOT NULL,
  CAPACITY INT NOT NULL ,
  CONDITION VARCHAR(50) NOT NULL
)




CREATE TABLE COACH_MEDICALSTATUS(
 C_MED_ID INT IDENTITY(1,1) PRIMARY KEY,
 M_ISSUE VARCHAR(50) NOT NULL,
 C_ID INT NOT NULL FOREIGN KEY REFERENCES COACH(C_ID),
 C_NAME VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES COACH(C_NAME),

 LEAVE INT,


 


)



CREATE TABLE PLAYER_MEDICALSTATUS(
 P_MED_ID INT IDENTITY(1,1) PRIMARY KEY,
 M_ISSUE VARCHAR(50) NOT NULL,
 P_ID INT NOT NULL FOREIGN KEY REFERENCES PLAYER(P_ID),
 P_NAME VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES PLAYER(P_NAME),

 LEAVE INT,


 


)

CREATE TABLE STAFF_MEDICALSTATUS(
 S_MED_ID INT IDENTITY(1,1) PRIMARY KEY,
 M_ISSUE VARCHAR(50) NOT NULL,
 S_ID INT NOT NULL FOREIGN KEY REFERENCES STAFF(S_ID),
 S_NAME VARCHAR(50) NOT NULL FOREIGN KEY REFERENCES STAFF(S_NAME),

 LEAVE INT,


 


)



